### ISSUE TITLE
Conflict with Aether mod

### ISSUE THREAD

**Issue by demielaurer** [FrozenBlock/TrailierTales#9]
The game gets stuck in loading screen when both TrailierTales-1.0.5+1.21.1 and aether-1.21.1-1.5.1-beta.3-fabric are present in mods folder

This is the only part of log that seems about this:
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: trailiertales:textures/entity/boat_banner_base/aether:skyroot.png
	at knot/net.minecraft.class_2960.method_45137(class_2960.java:285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60936(class_2960.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60655(class_2960.java:52) ~[client-intermediary.jar:?]
	at knot/net.frozenblock.trailiertales.TTConstants.id(TTConstants.java:78) ~[TrailierTales-1.0.5+1.21.1.jar:?]
	at knot/net.minecraft.class_881.trailierTales$getBannerBaseTextureLocation(class_881.java:1056) ~[client-intermediary.jar:?]
	at knot/com.google.common.collect.CollectCollectors.lambda$toImmutableMap$7(CollectCollectors.java:196) ~[guava-32.1.2-jre.jar:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at knot/net.minecraft.class_881.handler$djp000$trailiertales$trailierTales$init(class_881.java:1050) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_881.<init>(class_881.java:43) ~[client-intermediary.jar:?]
	at knot/net.hibiscus.naturespirit.client.HibiscusBoatEntityRenderer.<init>(HibiscusBoatEntityRenderer.java:17) ~[naturespirit-1.6.3-1.21.1.jar:?]
	at knot/net.hibiscus.naturespirit.client.NatureSpiritClient.lambda$registerBoatModel$21(NatureSpiritClient.java:147) ~[naturespirit-1.6.3-1.21.1.jar:?]
	at knot/net.minecraft.class_5619.redirect$blp000$fabric-rendering-v1$createEntityRenderer(class_5619.java:558) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5619.method_32174(class_5619.java:168) ~[client-intermediary.jar:?]
	at knot/it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.12.jar:?]
	at knot/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1004) ~[fastutil-8.5.12.jar:?]
	at knot/it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.12.jar:?]
	at knot/net.minecraft.class_5619.method_32176(class_5619.java:166) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_898.method_14491(class_898.java:447) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]

**Comment by HazeWorksOnFiveMServer** [comment]
Same here can Confirm

**Comment by AViewFromTheTop** [comment]
Will be fixed with a Resource Location try-catch thingy in 1.1
